'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import universe from '@/lib/universe.json';
import {requiredBars,ruleLabels} from '@/lib/rules';
import {RulesControl,type ActiveRules} from '@/components/rules-control';
import {analyze,type Bar,type Signal} from '@/lib/strategy';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Activity,ArrowUpRight,Search,SlidersHorizontal,Plug,Check,Minus,RefreshCw,X} from 'lucide-react';
const usd=(n?:number)=>n===undefined?'—':n.toLocaleString('en-US',{style:'currency',currency:'USD'});
const tone=(s?:string)=>s==='Qualified'?'green':s==='Watch'?'amber':s==='Not qualified'?'red':'neutral';

export default function Home(){
 const [activeRules,setActiveRules]=useState<ActiveRules|null>(null);
 const rules=activeRules?.rules;
 const labels=rules?rules.enabled_checks.map(id=>ruleLabels(rules)[id]):[];
 const [query,setQuery]=useState(''),[sector,setSector]=useState('All sectors'),[filter,setFilter]=useState('All setups'),[selected,setSelected]=useState('AAPL'),[setup,setSetup]=useState(false),[key,setKey]=useState(''),[secret,setSecret]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(0),[error,setError]=useState(''),[bars,setBars]=useState<Record<string,Bar[]>>({}),[scanned,setScanned]=useState(false),[started,setStarted]=useState(false);
 const abort=useRef<AbortController|null>(null);
 const signals=useMemo(()=>rules?Object.fromEntries(universe.filter(s=>bars[s.symbol]).map(s=>[s.symbol,analyze(bars[s.symbol],bars.SPY??[],rules)])) as Record<string,Signal>:{},[bars,rules]);
 const rows=useMemo(()=>universe.filter(s=>(sector==='All sectors'||s.sector===sector)&&(s.symbol+' '+s.name).toLowerCase().includes(query.toLowerCase())&&(filter==='All setups'||(signals[s.symbol]?.status??'No data')===filter)).sort((a,b)=>(signals[b.symbol]?.score??-1)-(signals[a.symbol]?.score??-1)||a.symbol.localeCompare(b.symbol)),[query,sector,filter,signals]);
 const stock=universe.find(s=>s.symbol===selected)!,sig=signals[selected];
 const qualified=Object.values(signals).filter(s=>s.status==='Qualified').length;
 const spy=bars.SPY??[],market=rules&&spy.length>=rules.market_sma_period?spy.at(-1)!.c>spy.slice(-rules.market_sma_period).reduce((sum,b)=>sum+b.c,0)/rules.market_sma_period:undefined;
 const date=spy.at(-1)?.t.slice(0,10);
 const marketFresh=rules&&spy.length>0&&(Date.now()-Date.parse(spy.at(-1)!.t))/86400000<=rules.max_data_age_days;
 useEffect(()=>()=>abort.current?.abort(),[]);
 async function scan(){
  if(!rules){setError("Load a valid rules Markdown file before scanning.");return;}
  if(!key.trim()||!secret.trim()){setSetup(true);return;}
  const controller=new AbortController();abort.current=controller;setBusy(true);setError('');setDone(0);setBars({});setScanned(false);setStarted(true);setSetup(false);setFilter('All setups');
  const collected:Record<string,Bar[]>={};
  try{
   async function batch(symbols:string[]){const res=await fetch('/api/bars',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbols,key:key.trim(),secret:secret.trim()}),signal:controller.signal});const data=await res.json() as {error?:string;bars:Record<string,Bar[]>};if(!res.ok)throw new Error(data.error??'Data request failed.');Object.assign(collected,data.bars);}
   await batch(['SPY']);if((collected.SPY?.length??0)<requiredBars(rules))throw new Error('SPY benchmark history is incomplete. No signals can be calculated.');
   for(let i=0;i<universe.length;i+=20){await batch(universe.slice(i,i+20).map(s=>s.symbol));setBars({...collected});setDone(Math.min(i+20,universe.length));}
   setScanned(true);
  }catch(e){setError(e instanceof Error&&e.name==='AbortError'?'Scan stopped. Results shown are partial.':e instanceof Error?e.message:'Scan failed.');}
  finally{setBusy(false);}
 }
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!ctx)return;const lifecycle=new AbortController();try{Promise.resolve(ctx.registerTool({name:'inspect_sp500_stock',description:'Select an S&P 500 stock and return its current calculated setup. Does not place trades or fetch data.',inputSchema:{type:'object',properties:{symbol:{type:'string'}},required:['symbol'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input:unknown){const symbol=(input as {symbol?:unknown})?.symbol;if(typeof symbol!=='string'||!universe.some(s=>s.symbol===symbol))throw new Error('Choose an exact S&P 500 symbol.');setSelected(symbol);return {symbol,signal:signals[symbol]??{status:'No data'}};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[signals]);
 return <main><header><div className="brand"><span className="brand-icon"><Activity size={23}/></span>SwingScope <span className="edition">S&P 500</span></div><button onClick={()=>setSetup(true)}><Plug size={16}/> {key&&secret?'Data connection':'Connect data'}</button></header><div className="workspace"><div className="title-row"><div><div className="eyebrow">DAILY / LONG SETUPS</div><h1>Find your next setup.</h1><p>One universe. Clear rules. A plan before every entry.</p></div>{busy?<button onClick={()=>abort.current?.abort()}><X size={16}/> Stop scan</button>:<button className="primary" disabled={!rules} onClick={scan}><RefreshCw size={16}/> Run screener</button>}</div><div className="stats"><div><span>Stock universe</span><strong>{universe.length}<small>S&P 500 share classes</small></strong></div><div><span>Qualifying setups</span><strong>{started?qualified:'—'}<small>{busy?'Partial scan in progress':scanned?`All ${labels.length} enabled checks pass`:started?'Partial results':'Connect data to calculate'}</small></strong></div><div><span>Market filter · SPY</span><strong>{market===undefined?'—':!marketFresh?'Stale':market?'Pass':'Fail'}<small>{date?`As of ${date}`:rules?`Above ${rules.market_sma_period}-day average`:'Rules not loaded'}</small></strong></div><div><span>Strategy</span><strong>{rules?`${rules.breakout_period}-day`:'—'}<small>{rules?.enabled_checks.includes('breakout')?'Breakout lookback':'Breakout check disabled'}</small></strong></div></div>
 <RulesControl active={activeRules} onChange={setActiveRules} disabled={busy}/><div className="notice" role="status"><span className="dot"/>{busy?<><b>Scanning {done} / {universe.length}</b> Fetching completed daily bars from Alpaca SIP…</>:scanned?<><b>Scan complete · {date}</b> Split-adjusted daily data. Today's incomplete bar is excluded.</>:started?<><b>Scan incomplete.</b> {done} of {universe.length} stocks processed. Unscanned stocks show no data.</>:<><b>Price data not connected.</b> Browse the universe now. Connect a free Alpaca account to calculate daily signals.</>}</div>{error&&<div className="error-box" role="alert">{error} <button onClick={()=>setSetup(true)}>Check connection</button></div>}
 <div className="surface"><section className="results"><div className="table-title"><h2>S&P 500 stocks <span>{rows.length}</span></h2><SlidersHorizontal size={18}/></div><div className="filters"><label className="search"><Search size={17}/><input aria-label="Search stocks" placeholder="Search symbol or company" value={query} onChange={e=>setQuery(e.target.value)}/></label><Select value={sector} onValueChange={v=>setSector(v??'All sectors')}><SelectTrigger aria-label="Sector"><SelectValue/></SelectTrigger><SelectContent>{['All sectors',...new Set(universe.map(s=>s.sector))].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><Select value={filter} onValueChange={v=>setFilter(v??'All setups')}><SelectTrigger aria-label="Setup status"><SelectValue/></SelectTrigger><SelectContent>{['All setups','Qualified','Watch','Not qualified','No data','Stale data','Insufficient data'].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div><div className="stock-scroll"><Table><TableHeader><TableRow>{['Company','Close',rules?`RSI (${rules.rsi_period})`:'RSI','Rel. volume','Setup'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(s=>{const signal=signals[s.symbol];return <TableRow key={s.symbol} data-state={selected===s.symbol?'selected':undefined}><TableCell><button className="stock-button" aria-pressed={selected===s.symbol} onClick={()=>setSelected(s.symbol)}><b>{s.symbol}</b><span>{s.name}</span></button></TableCell><TableCell>{usd(signal?.close)}</TableCell><TableCell>{signal?.rsi?.toFixed(1)??'—'}</TableCell><TableCell>{signal?.rvol===undefined?'—':signal.rvol.toFixed(2)+'×'}</TableCell><TableCell><span className={'badge '+tone(signal?.status)}>{signal?.status??'No data'}</span></TableCell></TableRow>})}</TableBody></Table>{!rows.length&&<p className="empty">No stocks match your filters. Try another sector or setup status.</p>}</div><div className="table-foot">Constituents snapshot · Sep 9, 2026 <span>Daily bars · USD</span></div></section>
 <aside className="detail"><div className="eyebrow">SETUP INSPECTOR <ArrowUpRight size={16}/></div><h2>{stock.symbol}</h2><p>{stock.name}</p><span className={'badge '+tone(sig?.status)}>{sig?.status??'Awaiting market data'}</span>{sig?.history.length?<><PriceChart bars={sig.history}/><p className="metadata">Daily close · last {sig.history.length} sessions · {sig.date}</p><h2>{usd(sig.close)}</h2></>:<div className="no-chart"><Activity size={32}/><p>Your price chart and entry plan<br/>will appear after a scan.</p></div>}{sig?.reason&&<p className="error">{sig.reason}</p>}
 {sig?.entry&&<><h3>Conditional next-session plan</h3><div className="plan"><div><span>Entry trigger</span><b>{usd(sig.entry)}</b></div><div><span>Initial stop</span><b>{usd(sig.stop)}</b></div><div><span>Illustrative {rules?(rules.target_atr/rules.stop_atr).toFixed(2):'—'}R target</span><b>{usd(sig.target)}</b></div><div><span>ATR ({rules?.atr_period})</span><b>{usd(sig.atr)}</b></div></div><p className="metadata">Trigger above the signal-day high. Recalculate after the next daily close. If price gaps above the trigger, reassess entry and risk; fills and stops are not guaranteed.</p></>}
 <h3>Entry checklist {sig?.checks.length?`· ${sig.score}/${labels.length}`:''}</h3>{labels.map((label,i)=>{const c=sig?.checks[i];return <div className={'rule '+(c?(c.pass?'pass':'fail'):'')} key={label}>{c?(c.pass?<Check size={15}/>:<X size={15}/>):<Minus size={15}/>}<div><span>{label}</span>{c&&<small>{c.value}</small>}</div></div>})}{!started&&<button className="full" onClick={()=>setSetup(true)}><Plug size={16}/> Connect free data</button>}{sig&&sig.status!=='Qualified'&&<p className="metadata">No entry plan issued. {sig.status==='Watch'?'Enabled context filters pass; wait for the remaining breakout or volume checks.':'All enabled checks and data-quality checks must pass.'}</p>}</aside></div>
 {rules&&<section className="method"><div><div className="eyebrow">ACTIVE ENTRY MODEL</div><h2>{rules.name}</h2><p>{labels.length} enabled checks. Disabled checks are excluded from qualification.</p></div><div><b>01 / Active checks</b><p>{labels.join(' · ')}</p></div><div><b>02 / Indicator definitions</b><p>Breakout and average volume exclude the signal day. EMA uses an SMA seed. RSI and ATR use Wilder smoothing. Relative strength compares stock and SPY returns over matching sessions.</p></div><div><b>03 / Plan the trade</b><p>Trigger: signal-day high + {rules.entry_buffer_atr} ATR. Stop: trigger − {rules.stop_atr} ATR. Illustrative target: trigger + {rules.target_atr} ATR. Maximum data age: {rules.max_data_age_days} calendar days.</p></div></section>}<div className="notes"><b>Before an entry</b><p>Check upcoming earnings, news, spreads and a current broker quote. Earnings are not connected in this version. The target is a planning assumption, not measured resistance or a predicted return. These thresholds are unvalidated; backtest and paper trade first.</p></div><footer><span>Current constituent snapshot, not a historical membership database. Refreshed manually; index changes after Sep 9, 2026 are not included.</span><div><a href="https://github.com/datasets/s-and-p-500-companies" target="_blank" rel="noreferrer">Constituents ↗</a> · <a href="https://docs.alpaca.markets/us/docs/market-data-faq" target="_blank" rel="noreferrer">Data source ↗</a></div></footer></div>
 <Dialog open={setup} onOpenChange={setSetup}><DialogContent className="connection"><DialogTitle>Connect free daily market data</DialogTitle><DialogDescription>Alpaca’s historical SIP feed covers US exchanges. A free account and API keys are required. This app only reads market data.</DialogDescription><ol><li>Create a free account at <a href="https://app.alpaca.markets/signup" target="_blank" rel="noreferrer">Alpaca ↗</a>.</li><li>Generate paper-account API keys in your dashboard.</li><li>Paste both values below and run the screener.</li></ol><label htmlFor="api-key">API key ID</label><input id="api-key" type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder="Your Alpaca key ID"/><label htmlFor="api-secret">Secret key</label><input id="api-secret" type="password" autoComplete="off" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Your Alpaca secret key"/><p className="metadata">Keys stay in this tab’s memory, pass through this app’s server to Alpaca for each scan, and are not saved. Reloading clears the connection. Account eligibility and data access depend on Alpaca.</p><button className="primary full" disabled={!key.trim()||!secret.trim()||busy||!rules} onClick={scan}>Connect & scan {universe.length} stocks</button>{key&&<button disabled={busy} onClick={()=>{setKey('');setSecret('');setBars({});setStarted(false);setScanned(false);setDone(0);setError('');}}>Disconnect & clear results</button>}<p className="metadata">Free historical SIP requests must end at least 15 minutes in the past. This screener excludes the current New York day entirely. No automatic trades are placed.</p></DialogContent></Dialog>
 </main>
}
function PriceChart({bars}:{bars:Bar[]}){const values=bars.map(b=>b.c),min=Math.min(...values),max=Math.max(...values),spread=max-min||1;const points=values.map((c,i)=>`${i/(values.length-1||1)*280},${115-(c-min)/spread*100}`).join(' ');return <svg className="chart" viewBox="0 0 280 130" role="img" aria-label="Daily closing prices over the last 63 sessions"><path d="M0 15 H280 M0 65 H280 M0 115 H280" stroke="#e4eae7" fill="none"/><polyline points={points} fill="none" stroke="#008066" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg>}

