'use client';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {SetupInspector} from '@/components/setup-inspector';
import {useLibrary,libraryRequest} from '@/components/library-client';
import {SavedScans,Watchlist,WatchStar,LibraryNotice} from '@/components/library-views';
import {makeSnapshot,type Snapshot} from '@/lib/library';
import {useEffect,useMemo,useRef,useState} from 'react';
import {universes,type UniverseId} from '@/lib/universes';
import {requiredBars,ruleLabels} from '@/lib/rules';
import {RulesControl,type ActiveRules} from '@/components/rules-control';
import {analyze,type Bar,type Signal} from '@/lib/strategy';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Activity,ArrowUpRight,Search,Plug,Check,Minus,RefreshCw,X} from 'lucide-react';
const usd=(n?:number)=>n===undefined?'—':n.toLocaleString('en-US',{style:'currency',currency:'USD'});
const tone=(s?:string)=>s==='Qualified'?'green':s==='Watch'?'amber':s==='Not qualified'?'red':'neutral';

export default function Home(){const [client]=useState(()=>new QueryClient({defaultOptions:{queries:{staleTime:15000}}}));return <QueryClientProvider client={client}><Sigma/></QueryClientProvider>;}
function Sigma(){
 const library=useLibrary();
 const [tab,setTab]=useState('screener');
 const [pendingSave,setPendingSave]=useState<{id:string;snapshot:Snapshot}|null>(null);
 const [saveMessage,setSaveMessage]=useState('');
 const [saving,setSaving]=useState(false);
 const [hydrated,setHydrated]=useState(false);
 useEffect(()=>setHydrated(true),[]);
 async function saveScan(item:{id:string;snapshot:Snapshot}){
  setSaving(true);setSaveMessage('Saving scan…');
  try{await libraryRequest('/api/library',{action:'saveScan',...item});setPendingSave(null);setSaveMessage(item.snapshot.complete?'Scan saved to your history.':'Partial scan saved; excluded from comparisons.');await library.refresh();}
  catch(e){setPendingSave(item);setSaveMessage('Scan is still in this tab. '+(e instanceof Error?e.message:'Save failed.'));}
  finally{setSaving(false);}
 }

 const [universeId,setUniverseId]=useState<UniverseId>('sp500');
 const index=universes[universeId],universe=index.stocks;
 const [serverConnected,setServerConnected]=useState(false);
 const [connectionLoading,setConnectionLoading]=useState(true);
 useEffect(()=>{const controller=new AbortController();fetch('/api/bars',{cache:'no-store',signal:controller.signal}).then(r=>r.ok?r.json():null).then(data=>setServerConnected((data as {serverConfigured?:boolean}|null)?.serverConfigured===true)).catch(()=>{}).finally(()=>setConnectionLoading(false));return()=>controller.abort();},[]);
 const [activeRules,setActiveRules]=useState<ActiveRules|null>(null);
 const rules=activeRules?.rules;
 const labels=rules?rules.enabled_checks.map(id=>ruleLabels(rules)[id]):[];
 const [query,setQuery]=useState(''),[sector,setSector]=useState('All sectors'),[filter,setFilter]=useState('All setups'),[selected,setSelected]=useState('AAPL'),[setup,setSetup]=useState(false),[key,setKey]=useState(''),[secret,setSecret]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(0),[error,setError]=useState(''),[bars,setBars]=useState<Record<string,Bar[]>>({}),[scanned,setScanned]=useState(false),[started,setStarted]=useState(false);
 const abort=useRef<AbortController|null>(null);
 const signals=useMemo(()=>rules?Object.fromEntries(universe.filter(s=>bars[s.symbol]).map(s=>[s.symbol,analyze(bars[s.symbol],bars.SPY??[],rules)])) as Record<string,Signal>:{},[universe,bars,rules]);
 const rows=useMemo(()=>universe.filter(s=>(sector==='All sectors'||s.sector===sector)&&(s.symbol+' '+s.name).toLowerCase().includes(query.toLowerCase())&&(filter==='All setups'||(signals[s.symbol]?.status??'No data')===filter)).sort((a,b)=>(signals[b.symbol]?.score??-1)-(signals[a.symbol]?.score??-1)||a.symbol.localeCompare(b.symbol)),[universe,query,sector,filter,signals]);
 const stock=universe.find(s=>s.symbol===selected)??universe[0],sig=signals[stock.symbol];
 function changeUniverse(value:string|null){if(busy||!value||!(value in universes))return;setUniverseId(value as UniverseId);setBars({});setSelected('AAPL');setQuery('');setSector('All sectors');setFilter('All setups');setScanned(false);setStarted(false);setDone(0);setError('');}
 const qualified=Object.values(signals).filter(s=>s.status==='Qualified').length;
 const spy=bars.SPY??[],market=rules&&spy.length>=rules.market_sma_period?spy.at(-1)!.c>spy.slice(-rules.market_sma_period).reduce((sum,b)=>sum+b.c,0)/rules.market_sma_period:undefined;
 const date=spy.at(-1)?.t.slice(0,10);
 const marketFresh=rules&&spy.length>0&&(Date.now()-Date.parse(spy.at(-1)!.t))/86400000<=rules.max_data_age_days;
 useEffect(()=>()=>abort.current?.abort(),[]);
 async function scan(){
  if(pendingSave){setError('Save or discard the pending snapshot before starting another scan.');return;}
  if(!rules){setError("Load a valid rules Markdown file before scanning.");return;}
  if(!serverConnected&&(!key.trim()||!secret.trim())){setSetup(true);return;}
  const controller=new AbortController();abort.current=controller;setBusy(true);setError('');setDone(0);setBars({});setScanned(false);setStarted(true);setSetup(false);setFilter('All setups');
  const collected:Record<string,Bar[]>={};let processed=0,complete=false;const scanId=crypto.randomUUID();const scanRules=activeRules!.markdown;
  try{
   async function batch(symbols:string[]){const res=await fetch('/api/bars',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(serverConnected?{symbols}:{symbols,key:key.trim(),secret:secret.trim()}),signal:controller.signal});const data=await res.json() as {error?:string;bars:Record<string,Bar[]>};if(!res.ok)throw new Error(data.error??'Data request failed.');Object.assign(collected,data.bars);}
   await batch(['SPY']);if((collected.SPY?.length??0)<requiredBars(rules))throw new Error('SPY benchmark history is incomplete. No signals can be calculated.');
   for(let i=0;i<universe.length;i+=20){await batch(universe.slice(i,i+20).map(s=>s.symbol));setBars({...collected});processed=Math.min(i+20,universe.length);setDone(processed);}
   complete=true;setScanned(true);
  }catch(e){setError(e instanceof Error&&e.name==='AbortError'?'Scan stopped. Results shown are partial.':e instanceof Error?e.message:'Scan failed.');}
  finally{
   try{if(processed>0){const results=Object.fromEntries(universe.slice(0,processed).map(s=>[s.symbol,analyze(collected[s.symbol]??[],collected.SPY??[],rules)]));await saveScan({id:scanId,snapshot:makeSnapshot(universeId,scanRules,results,collected.SPY?.at(-1)?.t.slice(0,10)??null,complete,processed)});}}catch{setSaveMessage('Could not prepare the saved scan. Results remain in this tab.');}finally{setBusy(false);}
  }
 }
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!ctx)return;const lifecycle=new AbortController();try{Promise.resolve(ctx.registerTool({name:'inspect_stock',description:'Select a stock in the currently selected index and return its current calculated setup. Does not place trades or fetch data.',inputSchema:{type:'object',properties:{symbol:{type:'string'}},required:['symbol'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input:unknown){const symbol=(input as {symbol?:unknown})?.symbol;if(typeof symbol!=='string'||!universe.some(s=>s.symbol===symbol))throw new Error('Choose an exact symbol from the selected index.');setSelected(symbol);return {symbol,signal:signals[symbol]??{status:'No data'}};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[signals,universe]);
 return <Tabs value={tab} onValueChange={v=>setTab(String(v))}><main><header><div className="brand"><span className="brand-icon"><Activity size={23}/></span>Sigma <span className="edition">{index.label}</span></div><button onClick={()=>setSetup(true)}><Plug size={16}/> {serverConnected?'Server data connected':key&&secret?'Data connection':'Connect data'}</button></header><div className="workspace"><TabsList className="main-tabs" aria-label="Sigma sections"><TabsTrigger value="screener">Screener</TabsTrigger><TabsTrigger value="saved">Saved scans</TabsTrigger><TabsTrigger value="watchlist">Watchlist</TabsTrigger></TabsList><LibraryNotice library={library}/><TabsContent value="screener" keepMounted><div className="title-row"><div><div className="eyebrow">DAILY / LONG SETUPS</div><h1>Find your next setup.</h1><p>Choose an index. Apply your rules. Review each setup.</p></div>{busy?<button onClick={()=>abort.current?.abort()}><X size={16}/> Stop scan</button>:<button className="primary" disabled={!rules||connectionLoading} onClick={scan}><RefreshCw size={16}/> Run screener</button>}</div><div className="stats"><div><span>Stock universe</span><strong>{universe.length}<small>{index.label} securities</small></strong></div><div><span>Qualifying setups</span><strong>{started?qualified:'—'}<small>{busy?'Partial scan in progress':scanned?`All ${labels.length} enabled checks pass`:started?'Partial results':'Connect data to calculate'}</small></strong></div><div><span>Market filter · SPY</span><strong>{market===undefined?'—':!marketFresh?'Stale':market?'Pass':'Fail'}<small>{date?`As of ${date}`:rules?`Above ${rules.market_sma_period}-day average`:'Rules not loaded'}</small></strong></div><div><span>Strategy</span><strong>{rules?`${rules.breakout_period}-day`:'—'}<small>{rules?.enabled_checks.includes('breakout')?'Breakout lookback':'Breakout check disabled'}</small></strong></div></div>
 {saveMessage&&<div className={pendingSave?'error-box':'save-notice'} role="status">{saveMessage}{pendingSave&&<div className="inline-actions"><button disabled={saving} onClick={()=>void saveScan(pendingSave)}>Retry save</button><button disabled={saving} onClick={()=>{setPendingSave(null);setSaveMessage('Unsaved snapshot discarded.');}}>Discard snapshot</button></div>}</div>}<RulesControl active={activeRules} onChange={setActiveRules} disabled={busy}/><div className="notice" role="status"><span className="dot"/>{busy?<><b>Scanning {done} / {universe.length}</b> Fetching completed daily bars from Alpaca SIP…</>:scanned?<><b>Scan complete · {date}</b> Split-adjusted daily data. Today's incomplete bar is excluded.</>:started?<><b>Scan incomplete.</b> {done} of {universe.length} stocks processed. Unscanned stocks show no data.</>:<><b>{connectionLoading?'Checking data connection…':serverConnected?'Server data connected.':'Price data not connected.'}</b> {serverConnected?'Run the screener to calculate daily signals.':'Browse the universe now. Connect a free Alpaca account to calculate daily signals.'}</>}</div>{error&&<div className="error-box" role="alert">{error} <button onClick={()=>setSetup(true)}>Check connection</button></div>}
 <div className="surface"><section className="results"><div className="table-title"><h2>{index.label} stocks <span>{rows.length}</span></h2><Select value={universeId} onValueChange={changeUniverse} disabled={busy}><SelectTrigger aria-label="Stock index"><SelectValue>{index.label}</SelectValue></SelectTrigger><SelectContent>{Object.entries(universes).map(([id,u])=><SelectItem key={id} value={id}>{u.label}</SelectItem>)}</SelectContent></Select></div><div className="filters"><label className="search"><Search size={17}/><input aria-label="Search stocks" placeholder="Search symbol or company" value={query} onChange={e=>setQuery(e.target.value)}/></label><Select value={sector} onValueChange={v=>setSector(v??'All sectors')}><SelectTrigger aria-label={index.classification}><SelectValue/></SelectTrigger><SelectContent>{['All sectors',...new Set(universe.map(s=>s.sector))].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><Select value={filter} onValueChange={v=>setFilter(v??'All setups')}><SelectTrigger aria-label="Setup status"><SelectValue/></SelectTrigger><SelectContent>{['All setups','Qualified','Watch','Not qualified','No data','Stale data','Insufficient data'].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div><div className="stock-scroll"><Table><TableHeader><TableRow>{['','Company','Close',rules?`RSI (${rules.rsi_period})`:'RSI','Rel. volume','Setup'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{(hydrated?rows:[]).map(s=>{const signal=signals[s.symbol];return <TableRow key={s.symbol} data-state={selected===s.symbol?'selected':undefined}><TableCell><WatchStar symbol={s.symbol} library={library}/></TableCell><TableCell><button className="stock-button" aria-pressed={selected===s.symbol} onClick={()=>setSelected(s.symbol)}><b>{s.symbol}</b><span>{s.name}</span></button></TableCell><TableCell>{usd(signal?.close)}</TableCell><TableCell>{signal?.rsi?.toFixed(1)??'—'}</TableCell><TableCell>{signal?.rvol===undefined?'—':signal.rvol.toFixed(2)+'×'}</TableCell><TableCell><span className={'badge '+tone(signal?.status)}>{signal?.status??'No data'}</span></TableCell></TableRow>})}</TableBody></Table>{!rows.length&&<p className="empty">No stocks match your filters. Try another sector or setup status.</p>}</div><div className="table-foot">Snapshot retrieved · {index.retrieved} <span>{index.classification} · USD</span></div></section>
 <SetupInspector stock={stock} sig={sig} rules={rules}/></div>
 {rules&&<section className="method"><div><div className="eyebrow">ACTIVE ENTRY MODEL</div><h2>{rules.name}</h2><p>{labels.length} enabled checks. Disabled checks are excluded from qualification.</p></div><div><b>01 / Active checks</b><p>{labels.join(' · ')}</p></div><div><b>02 / Indicator definitions</b><p>Breakout and average volume exclude the signal day. EMA uses an SMA seed. RSI and ATR use Wilder smoothing. Relative strength compares stock and SPY returns over matching sessions.</p></div><div><b>03 / Plan the trade</b><p>Trigger: signal-day high + {rules.entry_buffer_atr} ATR. Stop: trigger − {rules.stop_atr} ATR. Illustrative target: trigger + {rules.target_atr} ATR. Maximum data age: {rules.max_data_age_days} calendar days.</p></div></section>}<div className="notes"><b>Before an entry</b><p>Check upcoming earnings, news, spreads and a current broker quote. Earnings are not connected in this version. The target is a planning assumption, not measured resistance or a predicted return. These thresholds are unvalidated; backtest and paper trade first.</p></div><footer><span>{index.label} membership is a manually refreshed snapshot retrieved {index.retrieved}, not a historical membership database. Later index changes are not included.</span><div><a href={index.source} target="_blank" rel="noreferrer">Constituents ↗</a> · <a href="https://docs.alpaca.markets/us/docs/market-data-faq" target="_blank" rel="noreferrer">Data source ↗</a></div></footer></TabsContent><TabsContent value="saved"><SavedScans library={library}/></TabsContent><TabsContent value="watchlist"><Watchlist library={library} onInspect={symbol=>{setTab('screener');if(!universe.some(s=>s.symbol===symbol)){if(busy){setError('Stop the scan before switching indices.');return;}changeUniverse(universes.sp500.stocks.some(s=>s.symbol===symbol)?'sp500':'nasdaq100');}setSelected(symbol);}}/></TabsContent></div>
 <Dialog open={setup} onOpenChange={setSetup}><DialogContent className="connection"><DialogTitle>{serverConnected?'Server data connection':'Connect free daily market data'}</DialogTitle><DialogDescription>{serverConnected?'Alpaca credentials are configured securely on the server. You can scan without entering keys, including after a refresh.':'Alpaca’s historical SIP feed covers US exchanges. A free account and API keys are required. This app only reads market data.'}</DialogDescription>{!serverConnected&&<><ol><li>Create a free account at <a href="https://app.alpaca.markets/signup" target="_blank" rel="noreferrer">Alpaca ↗</a>.</li><li>Generate paper-account API keys in your dashboard.</li><li>Paste both values below and run the screener.</li></ol><label htmlFor="api-key">API key ID</label><input id="api-key" type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder="Your Alpaca key ID"/><label htmlFor="api-secret">Secret key</label><input id="api-secret" type="password" autoComplete="off" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Your Alpaca secret key"/><p className="metadata">Keys stay in this tab’s memory, pass through this app’s server to Alpaca for each scan, and are not saved. Reloading clears this temporary connection. For a permanent connection, configure ALPACA_API_KEY_ID and ALPACA_API_SECRET_KEY as server secrets. Account eligibility and data access depend on Alpaca.</p></>}<button className="primary full" disabled={(!serverConnected&&(!key.trim()||!secret.trim()))||busy||!rules||connectionLoading} onClick={scan}>{serverConnected?'Scan':'Connect & scan'} {universe.length} stocks</button>{!serverConnected&&key&&<button disabled={busy} onClick={()=>{setKey('');setSecret('');setBars({});setStarted(false);setScanned(false);setDone(0);setError('');}}>Disconnect & clear results</button>}<p className="metadata">Free historical SIP requests must end at least 15 minutes in the past. This screener excludes the current New York day entirely. No automatic trades are placed.</p></DialogContent></Dialog>
 </main></Tabs>
}
