'use client';
import {useEffect,useMemo,useState} from 'react';
import {Star,ArrowLeft,Download,Trash2} from 'lucide-react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {SetupInspector} from '@/components/setup-inspector';
import {compareScans,type SavedScan} from '@/lib/library';
import {allStocks,universes} from '@/lib/universes';
import {useSavedScan,type Library} from './library-client';
const usd=(v?:number)=>v===undefined?'—':v.toLocaleString('en-US',{style:'currency',currency:'USD'});
const date=(value:string)=>new Date(value).toLocaleString();
export function WatchStar({symbol,library}:{symbol:string;library:Library}){
 const watched=library.watchlist.some(s=>s.symbol===symbol);
 return <button className={'watch-star '+(watched?'starred':'')} aria-label={(watched?'Remove ':'Add ')+symbol+(watched?' from watchlist':' to watchlist')} aria-pressed={watched} disabled={library.mutating||!library.data} onClick={()=>void library.mutate({action:watched?'unwatch':'watch',symbol}).catch(()=>{})}><Star size={17} fill={watched?'currentColor':'none'}/></button>;
}
export function LibraryNotice({library}:{library:Library}){
 return library.isPending?<p className="metadata" role="status">Loading your library…</p>:library.error||library.mutationError?<div className="error-box" role="alert">{(library.error??library.mutationError)?.message}<button onClick={()=>void library.refetch()}>Retry</button></div>:null;
}
export function SavedScans({library}:{library:Library}){
 const [selected,setSelected]=useState<string|null>(null),[remove,setRemove]=useState<string|null>(null),[index,setIndex]=useState('all');
 const current=useSavedScan(selected),scan=current.data?.scan;
 const previousId=scan?.complete?library.scans.filter(s=>s.complete&&s.compatibility_key===scan.compatibility_key&&s.market_date&&scan.market_date&&s.market_date<scan.market_date).sort((a,b)=>(b.market_date??'').localeCompare(a.market_date??''))[0]?.id??null:null;
 const previous=useSavedScan(previousId);
 return <section className="library-view"><div className="library-heading"><div><h1>Saved scans</h1><p>Results and rules preserved at scan time. Latest 30 completed scans and 5 partial scans.</p></div><Select value={index} onValueChange={v=>{setIndex(v??'all');setSelected(null);}}><SelectTrigger aria-label="Saved scan index"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All indices</SelectItem>{Object.entries(universes).map(([id,u])=><SelectItem key={id} value={id}>{u.label}</SelectItem>)}</SelectContent></Select></div>
 {selected?<><button onClick={()=>setSelected(null)}><ArrowLeft size={16}/> Scan history</button>{current.isPending?<p role="status">Loading saved results…</p>:current.error?<div className="error-box" role="alert">{current.error.message}<button onClick={()=>void current.refetch()}>Retry</button></div>:scan&&<SnapshotView scan={scan} previous={previous.data?.scan} comparing={previous.isPending&&!!previousId} comparisonError={previous.error?.message} library={library}/>}</>:
 <div className="results"><Table><TableHeader><TableRow>{['Saved','Index / rules','Market date','Progress','Qualified',''].map((s,i)=><TableHead key={i}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{library.scans.filter(s=>index==='all'||s.universe_id===index).map(s=><TableRow key={s.id}><TableCell><button className="text-button" onClick={()=>setSelected(s.id)}>{date(s.created_at)}</button></TableCell><TableCell><b>{universes[s.universe_id].label}</b><small className="cell-note">{s.rules_name}</small></TableCell><TableCell>{s.market_date??'Unavailable'}</TableCell><TableCell><span className={'badge '+(s.complete?'green':'amber')}>{s.complete?'Complete':`Partial · ${s.processed}/${s.total}`}</span></TableCell><TableCell>{s.qualified}</TableCell><TableCell><button aria-label={'Delete scan from '+date(s.created_at)} onClick={()=>setRemove(s.id)}><Trash2 size={15}/></button></TableCell></TableRow>)}</TableBody></Table>{!library.isPending&&!library.error&&!library.scans.some(s=>index==='all'||s.universe_id===index)&&<div className="empty"><h2>No saved scans yet</h2><p>Run the screener. Results will be saved here automatically when the scan finishes.</p></div>}</div>}
 <Dialog open={!!remove} onOpenChange={open=>{if(!open)setRemove(null);}}><DialogContent><DialogTitle>Delete this saved scan?</DialogTitle><DialogDescription>This removes the saved results and their rules. Your watchlist stays unchanged.</DialogDescription><button disabled={library.mutating} onClick={()=>void library.mutate({action:'deleteScan',id:remove}).then(()=>setRemove(null)).catch(()=>{})}>Delete scan</button><button onClick={()=>setRemove(null)}>Cancel</button></DialogContent></Dialog></section>;
}
function SnapshotView({scan,previous,comparing,comparisonError,library}:{scan:SavedScan;previous?:SavedScan;comparing:boolean;comparisonError?:string;library:Library}){
 const [symbol,setSymbol]=useState(scan.snapshot.stocks[0].symbol),[query,setQuery]=useState(''),[filter,setFilter]=useState('All results');
 useEffect(()=>{setSymbol(scan.snapshot.stocks[0].symbol);setQuery('');setFilter('All results');},[scan.id]);
 const s=scan.snapshot,stock=s.stocks.find(s=>s.symbol===symbol)??s.stocks[0];
 const changes=previous?compareScans(scan,previous):null;
 const rows=useMemo(()=>s.stocks.filter(stock=>{
  if(!(stock.symbol+' '+stock.name).toLowerCase().includes(query.toLowerCase()))return false;
  if(filter==='Newly qualified')return changes?.newly.includes(stock.symbol);
  if(filter==='Still qualified')return changes?.still.includes(stock.symbol);
  if(filter==='No longer qualified')return changes?.lost.includes(stock.symbol);
  return filter==='All results'||s.signals[stock.symbol]?.status===filter;
 }),[s,query,filter,changes]);
 function download(){const url=URL.createObjectURL(new Blob([s.rulesMarkdown],{type:'text/markdown'}));const a=document.createElement('a');a.href=url;a.download='RULES-'+(scan.market_date??scan.id)+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <><div className="snapshot-banner"><div><b>{universes[s.universeId].label} · {scan.market_date??'No market date'} · {scan.complete?'Completed':'Partial'}</b><p>Historical snapshot saved {date(scan.created_at)}. Rules: {s.rules.name}. Entry plans apply to that signal date, not today.</p></div><button onClick={download}><Download size={16}/> Saved rules</button></div>
 {changes?<div className="comparison"><span>Compared with {previous?.market_date}</span><button onClick={()=>setFilter('Newly qualified')}>Newly qualified <b>{changes.newly.length}</b></button><button onClick={()=>setFilter('Still qualified')}>Still qualified <b>{changes.still.length}</b></button><button onClick={()=>setFilter('No longer qualified')}>No longer qualified <b>{changes.lost.length}</b></button><small>{changes.unavailable.length} stocks excluded because data was unavailable in either scan.</small></div>:<p className="metadata">{comparisonError?'Comparison unavailable: '+comparisonError:comparing?'Loading previous compatible scan…':scan.complete?'No earlier market date with the same rules and constituent list is saved yet.':'Partial scans are excluded from comparisons.'}</p>}
 <div className="surface"><section className="results"><div className="table-title"><h2>Saved results <span>{rows.length}</span></h2></div><div className="filters"><input className="library-search" aria-label="Search saved results" placeholder="Search symbol or company" value={query} onChange={e=>setQuery(e.target.value)}/><Select value={filter} onValueChange={v=>setFilter(v??'All results')}><SelectTrigger aria-label="Saved result status"><SelectValue/></SelectTrigger><SelectContent>{['All results','Qualified','Watch','Not qualified','Stale data','Insufficient data',...(changes?['Newly qualified','Still qualified','No longer qualified']:[])].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div><div className="stock-scroll"><Table><TableHeader><TableRow>{['','Company','Close','Checks','Setup'].map((h,i)=><TableHead key={i}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(stock=><TableRow key={stock.symbol} data-state={stock.symbol===symbol?'selected':undefined}><TableCell><WatchStar symbol={stock.symbol} library={library}/></TableCell><TableCell><button className="stock-button" onClick={()=>setSymbol(stock.symbol)}><b>{stock.symbol}</b><span>{stock.name}</span></button></TableCell><TableCell>{usd(s.signals[stock.symbol]?.close)}</TableCell><TableCell>{s.signals[stock.symbol]?.score??0}/{s.rules.enabled_checks.length}</TableCell><TableCell>{s.signals[stock.symbol]?.status??'Not scanned'}</TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="empty">No saved results match this filter.</p>}</div></section><SetupInspector stock={stock} sig={s.signals[stock.symbol]} rules={s.rules} historical/></div></>;
}
export function Watchlist({library,onInspect}:{library:Library;onInspect:(symbol:string)=>void}){
 const [editing,setEditing]=useState<string|null>(null),[note,setNote]=useState('');
 return <section className="library-view"><div className="library-heading"><div><h1>Watchlist</h1><p>Your stocks and notes, across both indices. Status comes from your latest completed saved scan containing that stock.</p></div><span className="badge neutral">{library.watchlist.length} stocks</span></div><div className="results"><Table><TableHeader><TableRow>{['','Stock','Latest close','Setup / date','Your note',''].map((s,i)=><TableHead key={i}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{library.watchlist.map(w=><TableRow key={w.symbol}><TableCell><WatchStar symbol={w.symbol} library={library}/></TableCell><TableCell><button className="stock-button" onClick={()=>onInspect(w.symbol)}><b>{w.symbol}</b><span>{allStocks.find(s=>s.symbol===w.symbol)?.name??w.symbol}</span></button></TableCell><TableCell>{usd(w.signal?.close)}</TableCell><TableCell>{w.signal?.status??'Not scanned'}<small className="cell-note">{w.market_date??'No saved data'}{w.rules_name?' · '+w.rules_name:''}</small></TableCell><TableCell><p className="watch-note">{w.note||'—'}</p></TableCell><TableCell><button onClick={()=>{setEditing(w.symbol);setNote(w.note);}}>Edit note</button></TableCell></TableRow>)}</TableBody></Table>{!library.isPending&&!library.error&&!library.watchlist.length&&<div className="empty"><Star size={28}/><h2>Your watchlist is empty</h2><p>Star a stock in the screener or a saved scan to keep it here.</p></div>}</div><Dialog open={!!editing} onOpenChange={open=>{if(!open)setEditing(null);}}><DialogContent><DialogTitle>Notes for {editing}</DialogTitle><DialogDescription>Private to your account. Up to 2,000 characters.</DialogDescription><Textarea aria-label="Watchlist note" maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/><button disabled={library.mutating} onClick={()=>void library.mutate({action:'watch',symbol:editing,note}).then(()=>setEditing(null)).catch(()=>{})}>Save note</button>{library.mutationError&&<p role="alert">{library.mutationError.message}</p>}</DialogContent></Dialog></section>;
}
