'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {parseRules,type Rules} from '@/lib/rules';
export type ActiveRules={rules:Rules;markdown:string;fileName:string};
export function RulesControl({active,onChange,disabled}:{active:ActiveRules|null;onChange:(v:ActiveRules)=>void;disabled:boolean}){
 const [open,setOpen]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const input=useRef<HTMLInputElement>(null);
 async function restore(signal?:AbortSignal){
  setLoading(true);setError('');try{const res=await fetch('/RULES.md',{cache:'no-store',signal});if(!res.ok)throw new Error('The default RULES.md could not be loaded. Load your own rules file or retry.');const markdown=await res.text();const rules=parseRules(markdown);onChange({rules,markdown,fileName:'RULES.md · published default'});}catch(e){if(e instanceof Error&&e.name!=='AbortError')setError(e.message);}finally{if(!signal?.aborted)setLoading(false);}
 }
 useEffect(()=>{const c=new AbortController();void restore(c.signal);return()=>c.abort();},[]);
 async function loadFile(file:File){
  setLoading(true);setError('');try{if(!file.name.toLowerCase().endsWith('.md'))throw new Error('Select a Markdown (.md) file.');if(file.size>65536)throw new Error('Rules file must be smaller than 64 KB.');const markdown=await file.text(),rules=parseRules(markdown);onChange({rules,markdown,fileName:file.name});}catch(e){setError((e instanceof Error?e.message:'Could not read this file.')+' Active rules were not changed.');}finally{setLoading(false);}
 }
 function download(){if(!active)return;const url=URL.createObjectURL(new Blob([active.markdown],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='RULES.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <><div className="rules-bar"><div><strong>Rules</strong><span>{active?.rules.name??(loading?'Loading rules…':'No valid rules loaded')}</span><small>{active?`${active.fileName} · ${active.rules.enabled_checks.length} enabled checks`:error||'A valid rules file is required before scanning.'}</small></div><button onClick={()=>setOpen(true)}>Rules & Markdown</button></div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="connection"><DialogTitle>Control your screening rules</DialogTitle><DialogDescription>Edit RULES.md in any text editor, then load it here. Valid settings immediately recalculate the stock history already in this tab.</DialogDescription><p className="metadata">The JSON block controls supported indicator periods, thresholds, enabled checks, entry buffer, stop, target and data age. Documentation outside the block does not change calculations.</p><div className="rules-actions"><button disabled={!active} onClick={download}>Download active RULES.md</button><button disabled={disabled||loading} onClick={()=>input.current?.click()}>Load .md file</button><button disabled={disabled||loading} onClick={()=>void restore()}>Restore published default</button></div><input ref={input} type="file" accept=".md,text/markdown,text/plain" hidden aria-label="Load Markdown rules file" disabled={disabled||loading} onChange={e=>{const file=e.target.files?.[0];if(file)void loadFile(file);e.target.value='';}}/>{loading&&<p role="status">Reading rules…</p>}{error&&<p className="error" role="alert">{error}</p>}{active&&<><p><b>Active:</b> {active.rules.name}</p><p className="metadata">{active.fileName}</p><pre className="rules-preview">{JSON.stringify(active.rules,null,2)}</pre></>}<p className="metadata">Files are read locally; they are not uploaded. Custom rules last for this tab session. Reloading restores the published default. After editing the file externally, load it again. To change the default for every session, replace the app’s public/RULES.md and republish.</p>{disabled&&<p className="metadata">Wait for the scan to finish or stop it before changing rules.</p>}</DialogContent></Dialog></>;
}
