import {Activity,ArrowUpRight,Check,X,Minus} from 'lucide-react';
import {ruleLabels,type Rules} from '@/lib/rules';
import type {StoredSignal} from '@/lib/library';
const usd=(n?:number)=>n===undefined?'—':n.toLocaleString('en-US',{style:'currency',currency:'USD'});
const tone=(s?:string)=>s==='Qualified'?'green':s==='Watch'?'amber':s==='Not qualified'?'red':'neutral';
export function SetupInspector({stock,sig,rules,historical=false}:{stock:{symbol:string;name:string};sig?:StoredSignal;rules?:Rules;historical?:boolean}){
const labels=rules?rules.enabled_checks.map(id=>ruleLabels(rules)[id]):[];
return <aside className="detail"><div className="eyebrow">SETUP INSPECTOR <ArrowUpRight size={16}/></div><h2>{stock.symbol}</h2><p>{stock.name}</p><span className={'badge '+tone(sig?.status)}>{sig?.status??'Awaiting market data'}</span>{sig?.history.length?<><PriceChart bars={sig.history}/><p className="metadata">Daily close · last {sig.history.length} sessions · {sig.date}</p><h2>{usd(sig.close)}</h2></>:<div className="no-chart"><Activity size={32}/><p>Your price chart and entry plan<br/>will appear after a scan.</p></div>}{sig?.reason&&<p className="error">{sig.reason}</p>}
 {sig?.entry&&<><h3>{historical?'Historical entry plan':'Conditional next-session plan'}</h3><div className="plan"><div><span>Entry trigger</span><b>{usd(sig.entry)}</b></div><div><span>Initial stop</span><b>{usd(sig.stop)}</b></div><div><span>Illustrative {rules?(rules.target_atr/rules.stop_atr).toFixed(2):'—'}R target</span><b>{usd(sig.target)}</b></div><div><span>ATR ({rules?.atr_period})</span><b>{usd(sig.atr)}</b></div></div><p className="metadata">Trigger above the signal-day high. Recalculate after the next daily close. If price gaps above the trigger, reassess entry and risk; fills and stops are not guaranteed.</p></>}
 <h3>Entry checklist {sig?.checks.length?`· ${sig.score}/${labels.length}`:''}</h3>{labels.map((label,i)=>{const c=sig?.checks[i];return <div className={'rule '+(c?(c.pass?'pass':'fail'):'')} key={label}>{c?(c.pass?<Check size={15}/>:<X size={15}/>):<Minus size={15}/>}<div><span>{label}</span>{c&&<small>{c.value}</small>}</div></div>})}{sig&&sig.status!=='Qualified'&&<p className="metadata">No entry plan issued. {sig.status==='Watch'?'Enabled context filters pass; wait for the remaining breakout or volume checks.':'All enabled checks and data-quality checks must pass.'}</p>}</aside>;
}
function PriceChart({bars}:{bars:{c:number}[]}){const values=bars.map(b=>b.c),min=Math.min(...values),max=Math.max(...values),spread=max-min||1;const points=values.map((c,i)=>`${i/(values.length-1||1)*280},${115-(c-min)/spread*100}`).join(' ');return <svg className="chart" viewBox="0 0 280 130" role="img" aria-label="Daily closing prices over the last 63 sessions"><path d="M0 15 H280 M0 65 H280 M0 115 H280" stroke="#e4eae7" fill="none"/><polyline points={points} fill="none" stroke="#008066" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg>}
